### ISSUE TITLE
Cannot create credentials

### ISSUE THREAD

**Issue by Xallt** [hansdoebel/n8n-nodes-ticktick#1]
Hey man, thanks for the plugin!

I'm encountering this issue: can't create the credentials for TickTick API as specified in your README

![image](https://github.com/hansdoebel/n8n-nodes-ticktick/assets/24624181/6675d568-dce5-4e2f-839a-df344405dd59)

It just doesn't see the option to create TickTick credentials. Any chance you know a quick fix?

**Comment by hansdoebel** [comment]
Hey, can you tell me which n8n version you're using? Do you at least have access to the custom TickTick node in the workflows?

**Comment by hansdoebel** [comment]
Thanks for the info, I'm glad to hear that! Just let me know if you have any more problems and i'll try to help :smile:
